In [1]:
import numpy as np

In [3]:
a = np.loadtxt('minutes_n_ingredients.csv', dtype = 'int32', delimiter=',', skiprows=1)

In [6]:
#задание 1

In [5]:
a[0:5, :]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

In [7]:
#задание 2

In [11]:
np.mean(a[:, 1]) # среднее значение второго столбца

21601.00169

In [10]:
np.mean(a[:, 2]) # среднее значение третьего столбца

9.05528

In [13]:
a[:, 1].min() #минимум второго столбца


0

In [14]:
a[:, 1].max() #максимум второго столбца

2147483647

In [15]:
a[:, 2].min() #минимум третьего столбца

1

In [16]:
a[:, 2].max() #максимум третьго столбца

39

In [19]:
np.median(a[:, 1]) #медиана второго столбца

40.0

In [20]:
np.median(a[:, 2]) #медиана третьего столбца

9.0

In [24]:
np.quantile(a[:, 1], 0.75) #третье задание

65.0

In [38]:
b = a[:, 1]

In [45]:
np.sum(b == 0) #количество нулевых вхождений (четвертое задание)

479

In [46]:
b

array([ 60,  25,  10, ...,  65,   5, 140])

In [47]:
c = b.copy()

In [48]:
c

array([ 60,  25,  10, ...,  65,   5, 140])

In [51]:
c[c==0] = 1 #замена всех нулей на еденицы

In [52]:
np.sum(c == 0) 

0

In [53]:
np.sum(c == 1)

716

In [54]:
len (np.unique(a[:,0])) # количество уникальных рецептов (задание пять)

100000

In [55]:
len (np.unique(a[:,2])) # количество уникальных количеств ингредиентов (задание шесть)

37

In [56]:
np.unique(a[:,2]) #уникальные количества ингредиентов

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 37, 39])

In [59]:
np.sum(a[:,2] < 6)

17262

In [64]:
compare_mask = a[:,2] < 6

In [65]:
g = a[compare_mask]

In [66]:
g # версия массива, содержащая информацию только о рецептах, состоящих не более чем из 5 ингредиентов(задание 7)

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

In [71]:
p = a[:,2] / c

In [72]:
p # количество ингредиентов на минуту каждого рецепта( ноль заменен на единицу)

array([0.26666667, 0.28      , 0.6       , ..., 0.23076923, 0.8       ,
       0.1       ])

In [73]:
p.max() # максимальное количество ингредиентов на минуту

24.0

In [87]:
sorted = np.sort(a)[::-1]

In [94]:
sorted = a[a[:, 1]. argsort ()[::-1]]

In [95]:
z = sorted[:100, :]

In [98]:
np.mean(z[:, 2]) # среднее количество ингредиентов для топ100 рецептов по продолжительности (задание 9)

6.61

In [ ]:
import random

In [118]:
i=0 # десятое задание

In [119]:
while i< 10:
    random_line = random.choice(a)
    print(random_line)
    i+=1

[80092    35     8]
[32438    10     6]
[95100    80    11]
[169983     25      8]
[263928    125     10]
[462281     22      7]
[117255     75      6]
[180072     40      5]
[113931     25     11]
[116964     80     10]


In [125]:
new_mask = a[:,2] < np.mean(a[:, 2])

In [126]:
len(a[new_mask]) # задание 11

58802

In [127]:
len(a[new_mask]) / len(a) # процент рецептов где количество ингредиентов меньше среднего

0.58802